### ISSUE TITLE
Question: How do I create an instance of a BigIntString?

### ISSUE THREAD

**Issue by Industrial** [jacob-alford/schemata-ts#297]
I have this in my Schema:
```ts
  minimumReward: S.BigIntFromString,
```

and get this error:

```
The types of 'input.minimumReward' are incompatible between these types.
    Type 'string' is not assignable to type 'BigIntString'.
      Type 'string' is not assignable to type 'Tagged<BigIntStringBrand>'.ts(2322)
```

**Comment by jacob-alford** [comment]
There are a few of ways to do this.

- Coerce a string you know to be a `BigIntString` using fp-ts 'unsafeCoerce'.  I use this a lot at work when I know what I'm coercing abides the underlying branded type.
- Cast the type as the right type.  Most of the time casting `number` to `Int`, `number` to `Float`, `Date` to `SafeDate` and `string` to `BigIntString` is castable with one `as` clause.
- Use `const guard = deriveInputGuard(S.BigIntString)` and use `guard.is()` to instruct typescript that the type is safely the underlying type.

Most of the time for branded types I know to be valid values, for example, `Int`'s, `Float`s, `SafeDate`'s, etc I just use `unsafeCoerce` because there is no concern about getting it wrong.  If the source of the type is unknown, i.e. from a network request then you should first `.decode()` from `deriveTranscoder()` or `.is()` from `deriveGuard()` / `deriveInputGuard()` to ensure that the type matches the expected type.

**Comment by jacob-alford** [comment]
Also, to clarify, casting and using `unsafeCoerce` should only be done when you write the value of the type yourself.

If the value is coming from a somewhere else, you should lift the function into an Either type use Transcoders to decode the value first.  This will guarantee type safety.  And alternatively you can use guard in this context for the same effect.

**Comment by Industrial** [comment]
Okay, thanks.
