### ISSUE TITLE
Type Error with Deno

### ISSUE THREAD

**Issue by Industrial** [jacob-alford/schemata-ts#310]
Hi.

I have this schema:

```ts
export const StatusNetworkOutputMessageSchema = NetworkOutputMessageBaseSchema
  .extend({
    command: S.Literal<['status']>('status'),
    payload: S.Struct({
      graph: GraphIDSchema,
      uptime: S.Number,
      started: S.Boolean,
      running: S.Boolean,
      debug: S.Boolean,
    }),
  })
```

and

```ts
        const output: StatusNetworkOutputMessage = StatusNetworkOutputMessageTranscoder.encode({
          protocol: 'network',
          command: 'status',
          payload: {
            graph: 'foo',
            debug: false,
            running: false,
            started: false,
            uptime: 1,
          },
        })
```

gives me the error:

```ts
Type 'number' is not assignable to type 'Float'.
  Type 'number' is not assignable to type 'Tagged<FloatBrand<-1.7976931348623157e+308, 1.7976931348623157e+308>>'.deno-ts(2322)
```

p.s. When I remove the type from `const output` and hover over it, the type is `const output: Either<Const<TranscodeErrors, O>, I>`. The transcoder is defined as `export const StatusNetworkOutputMessageTranscoder = deriveTranscoder(StatusNetworkOutputMessageSchema)`, so there might be an underlying type resolving difference between Deno and Node.js somehow..

**Comment by jacob-alford** [comment]
Hello 👋🏻 

This is actually by design.  Since the JavaScript number type also includes NaN, and +- Infinity, schemata has Float and Int as branded types to indicate that they're safe numbers (and also bring with them their bounds).

There will be a better way to make these numbers in 3.0, but for now the best way would be to `as Float` on `uptime`.  You can import that from `schemata-ts/float`
